version: "3.9"

volumes:
  pgdata:

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    env_file:
      - .env 
      - .flaskenv

    