version: "3.9"

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
      
  app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    env_file:
      - .env 
      - .flaskenv

    