version: "3.9"

services:
  app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://healthycup:hcapi@db:5432/healthycup
      FLASK_ENV: development
      FLASK_APP: app/main.py
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: healthycup
      POSTGRES_PASSWORD: hcapi
      POSTGRES_DB: healthycup
