name: Welcome!

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Congrats on adding your first issue! Look forward to resolving it!"
        pr-message: "Awesome! Congrats on your first PR!"
